## Numpy

### What is NumPy

- **NumPy** (Numerical Python) is an open source Python library that’s used in almost every field of science and engineering.

- **NumPy** is the universal standard for working with numerical data in Python.

- The **NumPy API** is used extensively in **Pandas**, **SciPy**, **Matplotlib**, **scikit-learn** and most other data science and scientific Python packages.

- The **NumPy** library contains multidimensional array and matrix data structures.

- **NumPy** adds powerful data structures to Python that guarantee efficient calculations with arrays and matrices and it supplies an enormous library of high-level mathematical functions that operate on these arrays and matrices.

In [ ]:
# Installing NumPy

#!pip install numpy

### How to import NumPy

In [ ]:
# To access NumPy and its functions import it in your Python code
import numpy as np

In [49]:
x = np.arange(6)
print(x)

[0 1 2 3 4 5]


In [50]:
type(x)

numpy.ndarray

In [51]:
x.shape

(6,)

In [52]:
y = x[np.newaxis, :]
print(y)

[[0 1 2 3 4 5]]


In [53]:
y.shape

(1, 6)

In [54]:
type(y.shape)

tuple

### NumPy X list Python

- While a **Python list** can contain different data types within a single list, all of the elements in a **NumPy array** should be homogeneous. 

- **NumPy arrays** are faster and more compact than **Python lists**. 

- An **array** consumes less memory and is convenient to use. 

- **NumPy** uses much less memory to store data and it provides a mechanism of specifying the data types.

### What is an array?

- An **array** is a central data structure of the **NumPy library**. 

- An **array** is a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element. 

- An array can be indexed by a **tuple** of nonnegative integers, by booleans, by another array, or by integers. 

- The **rank** of the array is the number of dimensions. 

- The **shape** of the array is a tuple of integers giving the size of the array along each dimension.

### Initializing NumPy arrays from Python lists

In [55]:
x = np.array([1, 2, 3, 4, 5, 6])
print(x)

[1 2 3 4 5 6]


In [56]:
lista = [1, 2, 3, 4, 5, 6]
x = np.array(lista)

In [57]:
print(lista)

[1, 2, 3, 4, 5, 6]


In [58]:
type(lista)

list

In [59]:
print(x)

[1 2 3 4 5 6]


In [60]:
type(x)

numpy.ndarray

In [61]:
x.shape

(6,)

In [63]:
m = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(m)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [64]:
type(m)

numpy.ndarray

In [65]:
m.shape

(3, 4)

In [66]:
m.ndim

2

### Accessing the elements in the array

In [70]:
lista = [1, 2, 3, 4, 5, 6]
x = np.array(lista)
print(x)
print(f'f[3] = {x[3]}')

[1 2 3 4 5 6]
f[3] = 4


In [71]:
print(f"lista = {lista}")

lista = [1, 2, 3, 4, 5, 6]


In [72]:
mt = m.T
print(mt)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [75]:
m.shape

(3, 4)

In [76]:
m.ndim

2

In [73]:
print(m[2].T)

[ 9 10 11 12]


In [74]:
mt.shape

(4, 3)

In [77]:
mt.ndim

2

### NumPy ndarray

- **NumPy ndarray class** is used to represent both matrices and vectors.

- The **shape** of an array is a tuple of non-negative integers that specify the sizes of each dimension.

- In **NumPy**, dimensions are called **axes**.

### How to create a basic array
 
 - np.array()
 - np.zeros() 
 - np.ones()
 - np.empty() 
 - np.arange() 
 - np.linspace() 
 - dtype

In [78]:
x = np.array([1, 2, 3])
print(f'x = {x}')

x = [1 2 3]


In [79]:
# array de zeros
x = np.zeros(2)
print(f'x = {x}')

x = [0. 0.]


In [83]:
# array de 1'set
x = np.ones(2)
print(f'x = {x}')

x = [1. 1.]


In [85]:
# create an array with a range of elements
x = np.arange(2,5)
print(f'x = {x}')

x = [2 3 4]


In [87]:
# create an array that contains a range of evenly spaced intervals
x = np.arange(2, 11, 2)
print(f'x = {x}')

x = [ 2  4  6  8 10]


In [88]:
# create an array with values that are spaced linearly in a specified interval
x = np.linspace(0, 10, num=5)
print(f'x = {x}')

x = [ 0.   2.5  5.   7.5 10. ]


In [89]:
# specifying your data type, int64, float64
x = np.ones(2, dtype=np.int64)
print(f'x = {x}')

x = [1 1]


### Adding, removing, and sorting elements

In [90]:
# start an array
x = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(x)

[2 1 5 3 7 4 6 8]


In [91]:
# returns a sorted copy of an array
y = np.sort(x)
print(y)

[1 2 3 4 5 6 7 8]


In [92]:
print(x)

[2 1 5 3 7 4 6 8]


In [93]:
# concatenate a and b
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])
z = np.concatenate((x, y))
print(z)

[1 2 3 4 5 6 7 8]


In [94]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
z = np.concatenate((x, y), axis=0)
print(z)

[[1 2]
 [3 4]
 [5 6]]


In [97]:
x = np.array([[1, 2],[3, 4]])
y = np.array([[5, 6],[7, 8]])
z = np.concatenate((x, y), axis=0)
print(z)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### Shape and size of an array

- **ndarray.ndim**: the number of axes, or dimensions, of the array.

- **ndarray.size**: the total number of elements of the array. 

- **ndarray.shape**: display a tuple of integers that indicate the number of elements stored along each dimension of the array.

- **arr.reshape()**: give a new shape to an array without changing the data.

In [98]:
x = np.array([1, 2, 3, 4])
x.ndim

1

In [99]:
x.shape

(4,)

In [100]:
x.size

4

In [101]:
m = np.array([[1, 2], [3, 4], [5,6]])
m.ndim

2

In [102]:
n = np.array([[[0, 1, 2, 3],[4, 5, 6, 7]],
              [[0, 1, 2, 3],[4, 5, 6, 7]],
              [[0 ,1 ,2, 3],[4, 5, 6, 7]]])
n.ndim

3

In [103]:
n.shape

(3, 2, 4)

In [104]:
n.size

24

In [105]:
m.size

6

In [106]:
x = np.arange(6)
print(x)

[0 1 2 3 4 5]


In [107]:
# reshape 'a' to an array with three rows and two columns
y = x.reshape(3, 2)
print(y)

[[0 1]
 [2 3]
 [4 5]]


In [112]:
z = np.reshape(x, newshape=(1, 6), order='C')

In [113]:
print(z)

[[0 1 2 3 4 5]]


In [114]:
z.shape

(1, 6)

In [115]:
x.shape

(6,)

In [116]:
w = np.reshape(x, newshape=(6, 1), order='C')
w.shape

(6, 1)

In [117]:
print(w)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


### Convert a 1D array into a 2D 

- **np.newaxis** and **np.expand_dims**: increase the dimensions of your existing array

- **np.newaxis**: increase the dimensions of your array by one dimension when used once

In [118]:
x = np.array([1, 2, 3, 4, 5, 6])
x.shape

(6,)

In [119]:
y = x[np.newaxis, :]
y.shape

(1, 6)

In [120]:
print(x)

[1 2 3 4 5 6]


In [121]:
print(y)

[[1 2 3 4 5 6]]


In [124]:
# convert a 1D array to a row vector
row_vector = x[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [128]:
# convert a 1D array to a column vector
col_vector = x[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


- Expanding an array by inserting a new axis at a specified position with **np.expand_dims**

In [129]:
x = np.array([1, 2, 3, 4, 5, 6])
x.shape

(6,)

In [130]:
y = np.expand_dims(x, axis=1)
y.shape

(6, 1)

In [131]:
z = np.expand_dims(x, axis=0)
z.shape

(1, 6)

### Indexing and slicing

In [132]:
x = np.array([1, 2, 3])

In [135]:
print(x[1])

2


In [134]:
print(x[0:2])

[1 2]


In [136]:
print(x[1:])

[2 3]


In [137]:
print(x[-2:])

[2 3]


- Select values from your array that fulfill certain conditions

In [138]:
m = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(m)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [139]:
# print all of the values in the array that are less than 5
print(m[m < 5])

[1 2 3 4]


In [140]:
type((m[m < 5]))

numpy.ndarray

In [141]:
# print numbers that are equal to or greater than 5
five_up = (m >= 5)
print(m[five_up])

[ 5  6  7  8  9 10 11 12]


In [142]:
type(five_up)

numpy.ndarray

In [143]:
type(m[five_up])

numpy.ndarray

In [144]:
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [145]:
# select elements that are divisible by 2
divisible_by_2 = m[m%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [146]:
# select elements that satisfy two conditions using the & and | operators:
x = m[(m > 2) & (m < 11)]
print(x)

[ 3  4  5  6  7  8  9 10]


### Basic array operations

- addition

- subtraction

- multiplication

- division

In [147]:
x = np.array([1, 2])
print(x)

[1 2]


In [149]:
y = np.ones(2, dtype=int)
print(y)

[1 1]


In [150]:
print(x + y)

[2 3]


In [151]:
print(x - y)

[0 1]


In [152]:
print(x * x)

[1 4]


In [153]:
print(x / y)

[1. 2.]


In [155]:
# sum of the elements in an array
x = np.array([1, 2, 3, 4])
x.sum()

10

In [156]:
# add the rows or the columns in a 2D array
x = np.array([[1, 1], [2, 2]])
print(x)

[[1 1]
 [2 2]]


In [157]:
x.sum(axis=0)

array([3, 3])

In [158]:
x.sum(axis=1)

array([2, 4])

In [159]:
# operation between a vector and a scalar
alpha = 1.6
x = np.array([1.0, 2.0])
alpha * x

array([1.6, 3.2])

### Array operations

- maximum

- minimum 

- sum

- mean 

- product 

- standard deviation

In [160]:
lista = [0.45,0.17,0.34,0.55,0.54,0.05,0.40,0.55,0.12,0.82,0.26,0.56]
x = np.array(lista)

In [168]:
x.size

12

In [161]:
x.max()

0.82

In [162]:
x.min()

0.05

In [163]:
x.sum()

4.8100000000000005

In [164]:
x.mean()

0.4008333333333334

In [165]:
x.std()

0.21332519515727366

In [171]:
y = x.reshape((3,4))
print(y)

[[0.45 0.17 0.34 0.55]
 [0.54 0.05 0.4  0.55]
 [0.12 0.82 0.26 0.56]]


In [172]:
y.max()

0.82

In [173]:
y.min()

0.05

In [174]:
y.sum()

4.8100000000000005

In [175]:
y.max(axis=0)

array([0.54, 0.82, 0.4 , 0.56])

In [176]:
y.max(axis=1)

array([0.55, 0.55, 0.82])

### Random number generation

- random.Generator class for random number generation

In [177]:
# the simplest way to generate random numbers
rng = np.random.default_rng()  
x = rng.random(10)
print(x)

[0.47371636 0.39983015 0.01064088 0.17391107 0.98431644 0.47483338
 0.06509928 0.86841947 0.26097734 0.12890586]


In [180]:
x = rng.random(size=(3,3)) 
print(x)

[[0.66998756 0.28055767 0.69869024]
 [0.6274062  0.01391695 0.95937292]
 [0.06665072 0.81545808 0.82182624]]


In [187]:
y = rng.random(size=(3,3))
print(y)

[[0.20585758 0.38197864 0.44590639]
 [0.41074634 0.92688429 0.6096153 ]
 [0.84515966 0.2718652  0.90098584]]


In [188]:
print(x + y)

[[0.87584514 0.66253631 1.14459663]
 [1.03815253 0.94080124 1.56898822]
 [0.91181038 1.08732328 1.72281208]]


In [189]:
print(x - y)

[[ 0.46412997 -0.10142098  0.25278385]
 [ 0.21665986 -0.91296734  0.34975762]
 [-0.77850895  0.54359287 -0.0791596 ]]


In [190]:
print(x * y)

[[0.13792202 0.10716704 0.31155044]
 [0.2577048  0.01289941 0.58484841]
 [0.0563305  0.22169467 0.74045381]]


In [191]:
x = rng.integers(5,size=(3,3)) 
y = rng.integers(9,size=(3,3))

In [192]:
print(x)

[[4 2 0]
 [2 0 4]
 [1 4 4]]


In [193]:
print(y)

[[6 8 2]
 [6 2 3]
 [0 7 7]]


### Transposing and reshaping a matrix

In [194]:
x = rng.integers(33, size=(3, 4)) 
print(x)

[[ 9  3 15  6]
 [28 23 13 26]
 [16 22  5  2]]


In [195]:
x.shape

(3, 4)

In [196]:
y = x.reshape(4,3)
print(y)

[[ 9  3 15]
 [ 6 28 23]
 [13 26 16]
 [22  5  2]]


In [197]:
y.shape

(4, 3)

In [198]:
z = x.transpose()
print(z)

[[ 9 28 16]
 [ 3 23 22]
 [15 13  5]
 [ 6 26  2]]


In [199]:
w = z.T
print(w)

[[ 9  3 15  6]
 [28 23 13 26]
 [16 22  5  2]]


In [200]:
help(max)

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value
    
    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.



### Linear algebra (numpy.linalg)

- The **NumPy linear algebra** functions rely on BLAS and LAPACK to provide efficient low level implementations of standard linear algebra algorithms. 

- Those libraries may be provided by **NumPy** itself using C versions of a subset of their reference implementations.

- See, https://numpy.org/doc/stable/reference/routines.linalg.html

***numpy.dot:***  matrix multiplication

In [2]:
import numpy as np

In [3]:
x = np.array([[1, 0], [0, 1]])
y = np.array([[4, 1], [2, 2]])

In [4]:
print(x)

[[1 0]
 [0 1]]


In [5]:
print(y)

[[4 1]
 [2 2]]


In [6]:
print(np.dot(x,y))

[[4 1]
 [2 2]]


In [7]:
print(x * y)

[[4 0]
 [0 2]]


***numpy.inner:*** inner product of two arrays

In [8]:
x = np.array([1,2,3])
y = np.array([0,1,0])

In [9]:
print(x)

[1 2 3]


In [10]:
print(y)

[0 1 0]


In [11]:
print(np.inner(x, y))

2


***numpy.linalg.det:*** compute the determinant of an array

In [12]:
x = np.array([[1, 2], [3, 4]])
print(x)

[[1 2]
 [3 4]]


In [13]:
np.linalg.det(x)

-2.0000000000000004

In [14]:
m = np.array([[1,2,3,4,5], [3,4,5,6,7],[4,5,6,7,8],[0,8,7,6,5],[4,3,5,2,6]])
print(m)
print(m.shape)

[[1 2 3 4 5]
 [3 4 5 6 7]
 [4 5 6 7 8]
 [0 8 7 6 5]
 [4 3 5 2 6]]
(5, 5)


In [15]:
np.linalg.det(m)

0.0

***numpy.linalg.inv:*** compute the (multiplicative) inverse of a matrix

In [16]:
# import function inv
from numpy.linalg import inv

In [17]:
x = np.array([[1., 2.], [3., 4.]])
print(x)

[[1. 2.]
 [3. 4.]]


In [18]:
xinv = np.linalg.inv(x)
print(xinv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [19]:
xinv = np.linalg.inv(m)
print(xinv)

LinAlgError: Singular matrix

In [20]:
# checking if xinv is the inverse of x
np.allclose(np.dot(x, xinv), np.eye(2))

True

***numpy.linalg.solve:*** solve a linear matrix equation

Consider the system of linear equations

$
\left\{
\begin{matrix}
x_0 & + & 2 x_1 & = & 1 \\
3 x_0 & + & 5 x_1 & = & 2 \\
\end{matrix}
\right.
$

a = 
$
\left[
\begin{matrix}
1 &  & 2 \\
3 &  & 5 \\
\end{matrix}
\right]
$
 
b = 
$
\left[
\begin{matrix}
1 \\
2 \\
\end{matrix}
\right]
$

In [21]:
a = np.array([[1, 2], [3, 5]])
b = np.array([1, 2])
x = np.linalg.solve(a, b)
print(x)

[-1.  1.]


In [22]:
# Check that the solution is correct
np.allclose(np.dot(a, x), b)

True

### Working with mathematical formulas

- The ease of implementing mathematical formulas that work on arrays is one of the things that make NumPy so widely used in the scientific Python community.

***Example:*** The mean square error formula
$$
error = \dfrac{1}{n} \sum_{i=1}^{n} (predicton_i - label_i)^2
$$

In [24]:
prediction = np.array([1,1,1])
label = np.array([1,2,3])

In [25]:
def error(prediction, label):
    n = len(label)
    error = (1/n) * np.sum(np.square(prediction-label))
    print(error)

In [26]:
error(prediction, label)

1.6666666666666665
